### ISSUE TITLE
Java process executing 'vagrant up' on Windows unable to terminate when streaming stdout and stderr to console

### ISSUE THREAD

**Issue by hferentschik** [dustymabe/vagrant-sshfs#41]
This is a follow up to issue #31. Before switching to win32-process the sftp-server and ssh commands would terminate one the executing Java process was forcefully terminated. This is not happening anymore. However, the thread streaming stdout and stderr still does not terminate and waits on a lock indefinitely.

**Comment by hferentschik** [comment]
Here is a Java class to re-produce the issue:

    import java.io.*;
    import java.util.Map;
    
    class StreamGobbler extends Thread {
        InputStream is;
        String type;
    
        StreamGobbler(InputStream is, String type) {
            this.is = is;
            this.type = type;
        }
    
        public void run() {
            try {
                InputStreamReader isr = new InputStreamReader( is );
                BufferedReader br = new BufferedReader( isr );
                String line = null;
                while ( !Thread.currentThread().isInterrupted() && ( line =     br.readLine() ) != null ) {
                    System.out.println( type + ">" + line );
                }
            }
            catch ( IOException ioe ) {
                ioe.printStackTrace();
            }
            System.out.println( "output thread ending" );
    
        }
    }
    
    public class ProcessLauncher {
        public static void main(String args[]) throws Exception {
            try {
                ProcessBuilder pb = new ProcessBuilder( "vagrant", "up" );
                pb.directory(new File("C:\\Users\\hardy\\work\\misc\\ruby-pipes"));
                pb.redirectErrorStream( true );
                Map<String, String> env = pb.environment();
                // set environment variable u
                env.put("SUB_USERNAME", "foo");
                env.put("SUB_PASSWORD", "bar");
                //env.put("VAGRANT_LOG", "debug");
    
                Process proc = pb.start();
    
                StreamGobbler outputGobbler = new StreamGobbler(proc.getInputStream(),     "OUTPUT");
                outputGobbler.start();
    
                int exitVal = proc.waitFor();
                System.out.println( "process returned:" + exitVal );
    
                outputGobbler.join();
    
                proc.destroy();
                System.out.println( "done" );
            }
            catch ( Throwable t ) {
                t.printStackTrace();
            }
        }
    }

**Comment by dustymabe** [comment]
ok - so after reading way more than I ever wanted to about the way windows handles process creation, I now understand the problem.

We are passing in filehandles to the call to createprocess (https://github.com/dustymabe/vagrant-sshfs/blob/18f1edfc3d0e02558bd23307f6d2bda2b4d3660d/lib/vagrant-sshfs/cap/guest/linux/sshfs_forward_mount.rb#L182). On windows, if no filehandle is passed then no files get inherited by default, but if any filehandle is passed to a spawned process (as we are doing) then all files that are set as inheritable will get inherited. It just so happens that all handles are inheritable by default.

See bInheritHandles from https://msdn.microsoft.com/en-us/library/windows/desktop/ms682425(v=vs.85).aspx

The java process is getting up because stdout and stderr are shared with the spawned processes. If we set those two procs as not inheritable by default then we don't have this problem. However, as a good practice we'll not only set stdout and stderr as not inheritable, but all of the other open file handles as well.
