### ISSUE TITLE
set up after reboots

### ISSUE THREAD

**Issue by cgwalters** [dustymabe/vagrant-sshfs#47]
If I reboot my box out of band of vagrant (e.g. `rpm-ostree upgrade -r`), sshfs doesn't get set up again.  I think we should look at installing a systemd unit file.

**Comment by dustymabe** [comment]
So the only problem with this is the fact that by default we are using sshfs "slave mounts" so that we actually do some of the setup for this on the host, outside of the guest. A good explanation of this is in the commit message https://github.com/dustymabe/vagrant-sshfs/commit/a57960972764134d97db0438cfaa9e3a2e31eb2c, it allows us to not have to set up authentication back into the host machine or even require an ssh daemon to be running.

Here is another place I try to document how we "wire things up" https://github.com/dustymabe/vagrant-sshfs/blob/0070e4356c87337c28a6f3715a2f52adf84827b6/lib/vagrant-sshfs/cap/guest/linux/sshfs_forward_mount.rb#L207-L219

What I do for a situation like this is simply type `vagrant sshfs` in your vagrant directory. This aliases to `vagrant sshfs --mount` and will mount all sshfs folders just like if you had done a `vagrant up`.

Thoughts?

**Comment by dustymabe** [comment]
@cgwalters - does my explanation above help describe the complexity involved?

**Comment by dustymabe** [comment]
> @cgwalters - does my explanation above help describe the complexity involved?

?

**Comment by cgwalters** [comment]
Yeah, no worries.  I've trained myself mostly to do `vagrant halt; vagrant up` anyways.  I could probably switch to `vagrant sshfs && vagrant ssh`.  Will try that.
