### ISSUE TITLE
How to support bidirectional syncing?

### ISSUE THREAD

**Issue by mcandre** [dustymabe/vagrant-sshfs#90]
Hello,

I am keen to configure my Vagrant boxes so that folders are synced both ways, so that I can rely on the box to automatically push source code changes from the host to the guest, and automatically pull binary application changes back to the host. I see in the vagrant-sshfs documentation that both forms are supported individually, but I am curious if there is a way to enable both host->guest and guest->host syncing simultaneously for a Vagrant box.

Does this make sense? Essentially, I want my Vagrant boxes to behave like Docker, where bidirectional syncing is available.

**Comment by dustymabe** [comment]
You should think of sshfs as a network filesystem. The files only live in one place so there is no real `bi-directional` syncing that happens (although that appears to be the case because files are transparently accessible from host and guest at the same time).

The only difference between the two implementations in vagrant-sshfs comes down to a question of where you want your files to actually live; on the host or on the guest. If I share a folder from my host into my guest I can still access the files on the host and from inside the guest at the same time, but the files *live* on the host. If I destroy the guest, the files will continue to exist on my host. 

> Does this make sense? Essentially, I want my Vagrant boxes to behave like Docker, where bidirectional syncing is available.

Yes, it makes sense. As mentioned above, though, I think `bidirectional syncing` is the wrong term to use. Two copies on the files don't exist, they're just accessible from two different places, which is what you want.

**Comment by dustymabe** [comment]
closing this as clarification was provided in the previous comment and no code work needs to be done
